CREATE TABLE carts (
    uuid VARCHAR(255) PRIMARY KEY NOT NULL,
    total INT NOT NULL,

    user_id VARCHAR(255) NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(uuid) ON DELETE CASCADE,
    item_id VARCHAR(255) NOT NULL,
    FOREIGN KEY(item_id) REFERENCES items(uuid) ON DELETE CASCADE
);
